sudo: required
services:
    - docker

before_install:
    - docker build -t chendu36/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true chendu36/react-test npm test

after_success:
    - docker build -t chendu36/multi-client ./client
    - docker build -t chendu36/multi-nginx ./nginx
    - docker build -t chendu36/multi-server ./server
    - docker build -t chendu36/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #Take those images and push them to docker hub
    - docker push chendu36/multi-nginx
    - docker push chendu36/multi-server
    - docker push chendu36/multi-worker
    - docker push chendu36/multi-client

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-us-east-1-216883378532
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY    
